spring:
  application:
    name: task-checker-service

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: 8085

springdoc:
  api-docs:
    enabled: true
    path: /task-checker-service/v1/api-docs
