services:
  monolith-postgres:
    image: postgres:16-alpine
    container_name: monolith-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-courses}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - monolith_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-courses}"]
      interval: 10s
      timeout: 5s
      retries: 10

  monolith-mvp:
    image: ${APP_IMAGE:?APP_IMAGE is required}
    pull_policy: always
    container_name: monolith-mvp
    restart: unless-stopped
    depends_on:
      monolith-postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-pg,mail-smtp}
      SPRING_DATASOURCE_URL: jdbc:postgresql://monolith-postgres:5432/${POSTGRES_DB:-courses}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      APP_MAIL_FROM: ${APP_MAIL_FROM:-kirillporozoff@yandex.ru}
      APP_MAIL_INVITE_BASE_URL: ${APP_MAIL_INVITE_BASE_URL:-http://localhost:8099}
      APP_STORAGE_ROOT_DIR: ${APP_STORAGE_ROOT_DIR:-/opt/app/data}
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST:-smtp.yandex.ru}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT:-465}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME:-kirillporozoff}
      APP_SECURITY_JWT_SECRET: ${APP_SECURITY_JWT_SECRET:?APP_SECURITY_JWT_SECRET is required}
      APP_BOOTSTRAP_ADMIN_PASSWORD: ${APP_BOOTSTRAP_ADMIN_PASSWORD:?APP_BOOTSTRAP_ADMIN_PASSWORD is required}
      SPRING_MAIL_PROTOCOL: ${SPRING_MAIL_PROTOCOL:-smtps}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:-true}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE:-true}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD:?SPRING_MAIL_PASSWORD is required}
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:-200MB}
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:-200MB}
    ports:
      - "${APP_PORT:-8099}:8099"
    volumes:
      - monolith_files_data:/opt/app/data

volumes:
  monolith_pg_data:
  monolith_files_data:
