spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: security-service-login-register
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/api/v1/auth/login, /api/v1/auth/register, /api/v1/auth/token/validate
        - id: security-service-login-register
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - JwtAuthenticationFilter
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - JwtAuthenticationFilter
        - id: mentor-catalog-service
          uri: lb://MENTOR-CATALOG-SERVICE
          predicates:
            - Path=/api/v1/mentors/**
          filters:
            - JwtAuthenticationFilter
        - id: personal-account-service
          uri: lb://PERSONAL-ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/user/account/**
          filters:
            - JwtAuthenticationFilter
        - id: minio-route
          uri: ${MINIO_URL:http://localhost:9000}
          predicates:
            - Path=/media/**
          filters:
            - StripPrefix=1
        - id: communication-service
          uri: lb://COMMUNICATION-SERVICE
          predicates:
            - Path=/api/v1/chats/**, /api/v1/messages/**
          filters:
            - JwtAuthenticationFilter
        - id: courses-service
          uri: lb://COURSES-SERVICE
          predicates:
            - Path=/api/v1/courses/**
          filters:
            - JwtAuthenticationFilter
        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/api/v1/media/**
          filters:
            - JwtAuthenticationFilter
        - id: progress-service
          uri: lb://PROGRESS-SERVICE
          predicates:
            - Path=/api/v1/progress/**
          filters:
            - JwtAuthenticationFilter
        - id: task-checker-service
          uri: lb://TASK-CHECKER-SERVICE
          predicates:
            - Path=/api/v1/task-checker/**
          filters:
            - JwtAuthenticationFilter
        - id: websocket-route
          uri: lb://COMMUNICATION-SERVICE  # Целевой WebSocket-сервис (например, chat-service)
          predicates:
            - Path=/ws/**  # Путь для WebSocket-соединений
        # OPENAPI PATHS
        - id: security-service-openapi
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security-service/v1/api-docs
        - id: mentor-catalog-service-openapi
          uri: lb://MENTOR-CATALOG-SERVICE
          predicates:
            - Path=/mentor-catalog-service/v1/api-docs
        - id: communication-service-openapi
          uri: lb://COMMUNICATION-SERVICE
          predicates:
            - Path=/communication-service/v1/api-docs
        - id: users-service-openapi
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/v1/api-docs
        - id: courses-service-openapi
          uri: lb://COURSES-SERVICE
          predicates:
            - Path=/courses-service/v1/api-docs
        - id: media-service-openapi
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/media-service/v1/api-docs
        - id: personal-account-service-openapi
          uri: lb://PERSONAL-ACCOUNT-SERVICE
          predicates:
            - Path=/personal-account-service/v1/api-docs
        - id: progress-service-openapi
          uri: lb://PROGRESS-SERVICE
          predicates:
            - Path=/progress-service/v1/api-docs
        - id: task-checker-service-openapi
          uri: lb://TASK-CHECKER-SERVICE
          predicates:
            - Path=/task-checker-service/v1/api-docs

  application:
    name: API-GATEWAY
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:fq4Rmz5Elc7pJZ8s3YvvKnmn0lk2v04taJOVjUkEb16z5ckSdZ}

service-discovery:
  security-service:
    name: SECURITY-SERVICE

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    ru.just: DEBUG

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: security-service
        url: /security-service/v1/api-docs
      - name: mentor-catalog-service
        url: /mentor-catalog-service/v1/api-docs
      - name: communication-service
        url: /communication-service/v1/api-docs
      - name: courses-service
        url: /courses-service/v1/api-docs
      - name: media-service
        url: /media-service/v1/api-docs
      - name: personal-account-service
        url: /personal-account-service/v1/api-docs
      - name: progress-service
        url: /progress-service/v1/api-docs
      - name: task-checker-service
        url: /task-checker-service/v1/api-docs
      - name: users-service
        url: /users-service/v1/api-docs
