-- =====================================================================
-- ЕДИНАЯ МИГРАЦИЯ СХЕМЫ ПРОЕКТА (актуальное состояние)
--
-- В этом файле собрана полная структура БД для MVP:
-- 1) пользователи и авторизация
-- 2) курсы/уроки/сабмишены
-- 3) группы и membership (org-структура через группы)
-- 4) назначение ревьюверов
--
-- Важно:
-- - company/department/position НЕ храним в users,
--   эти данные задаются только через группы (type = COMPANY/DEPARTMENT/POSITION).
-- - id групп = UUID.
-- =====================================================================

-- ---------------------------
-- Пользователи
-- ---------------------------
create table if not exists users (
    id bigint generated by default as identity primary key,
    full_name varchar(255) not null,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    role varchar(50) not null,
    enabled boolean not null default true,
    activated boolean not null default true,

    -- Доп. поля для профиля и CSV-обмена
    lang varchar(255),
    phone varchar(255),
    comment varchar(2000),
    avatar_file_path varchar(1000),
    created_at timestamp,
    created_by varchar(255),
    last_visit timestamp,
    deactivated_at timestamp,
    deactivated_by varchar(255)
);

-- ---------------------------
-- Разделы каталога
-- ---------------------------
create table if not exists sections (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description varchar(4000),
    priority integer not null
);

-- ---------------------------
-- Курсы
-- ---------------------------
create table if not exists courses (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description varchar(4000),
    author_full_name varchar(255),
    cover_file_path varchar(1000),
    passing_threshold_percent integer not null,
    deadline_days integer,
    deadline_at timestamp,
    lessons_free_order boolean not null,
    allow_continue_after_fail boolean not null,
    block_after_deadline boolean not null,
    keep_access_after_deadline boolean not null,
    include_in_overall_stats boolean not null,
    created_by_admin_id bigint not null,
    section_id bigint,
    constraint fk_course_section foreign key (section_id) references sections(id)
);

create index if not exists idx_courses_section_id on courses(section_id);

-- ---------------------------
-- Зачисления
-- ---------------------------
create table if not exists enrollments (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    course_id bigint not null,
    enrolled_at timestamp not null,
    started_at timestamp,
    completed_at timestamp,
    unique (user_id, course_id)
);

-- ---------------------------
-- Уроки (single-table inheritance)
-- ---------------------------
create table if not exists lessons (
    id bigint generated by default as identity primary key,
    lesson_kind varchar(31) not null,
    course_id bigint not null,
    position integer not null,
    title varchar(255) not null,
    description varchar(4000),
    stop_lesson boolean not null,
    blocked_during_attempt boolean not null,
    attempt_limit integer,
    time_limit_minutes integer,
    lesson_type varchar(50) not null,
    full_points integer not null,
    partial_points integer not null,

    -- Теория
    theory_content_type varchar(50),
    theory_content TEXT,

    -- Практика
    passing_threshold_percent integer,
    evaluate_by_correct_count boolean,
    random_question_count integer,
    shuffle_on_every_attempt boolean,
    show_question_status boolean,
    show_correct_answers_after_completion boolean,

    unique (course_id, position)
);

create table if not exists practice_questions (
    id bigint generated by default as identity primary key,
    lesson_id bigint not null,
    question_index integer not null,
    question_type varchar(50),
    question_text varchar(4000) not null,
    options_raw varchar(4000),
    correct_answers_raw varchar(2000),
    trainer_hint varchar(4000),
    full_points integer not null,
    partial_points integer not null
);

-- ---------------------------
-- Ответы по урокам
-- ---------------------------
create table if not exists lesson_submissions (
    id bigint generated by default as identity primary key,
    lesson_id bigint not null,
    student_id bigint not null,
    answer_raw varchar(4000),
    status varchar(50) not null, -- COMPLETE / INCOMPLETE / PENDING_REVIEW
    passed boolean not null,
    points_awarded integer not null default 0,
    submitted_at timestamp not null,
    reviewed_by_admin_id bigint,
    reviewed_at timestamp,
    review_comment varchar(2000)
);

create table if not exists lesson_submission_status_history (
    id bigint generated by default as identity primary key,
    submission_id bigint not null,
    from_status varchar(50),
    to_status varchar(50) not null,
    changed_by_admin_id bigint,
    changed_at timestamp not null,
    comment varchar(2000),
    constraint fk_submission_status_history_submission
        foreign key (submission_id) references lesson_submissions(id)
        on delete cascade
);

create index if not exists idx_submission_status_history_submission_id
    on lesson_submission_status_history(submission_id);

-- ---------------------------
-- Токены установки пароля (инвайт)
-- ---------------------------
create table if not exists password_setup_tokens (
    id bigint generated by default as identity primary key,
    token varchar(200) not null unique,
    user_id bigint not null,
    created_at timestamp not null,
    used_at timestamp
);

-- ---------------------------
-- Группы (org-структура)
-- ---------------------------
create table if not exists learning_groups (
    id uuid primary key,
    title varchar(255) not null,
    type varchar(50) not null
);

-- Запрещаем дубли одной и той же группы по title+type
create unique index if not exists uk_learning_groups_title_type
    on learning_groups(title, type);

-- ---------------------------
-- Membership пользователей в группах
-- ---------------------------
create table if not exists group_memberships (
    id bigint generated by default as identity primary key,
    group_id uuid not null,
    user_id bigint not null,
    constraint uk_group_user unique (group_id, user_id)
);

create table if not exists group_course_assignments (
    id bigint generated by default as identity primary key,
    group_id uuid not null,
    course_id bigint not null,
    created_at timestamp not null,
    constraint uk_group_course_assignment unique (group_id, course_id),
    constraint fk_group_course_assignment_group foreign key (group_id) references learning_groups(id) on delete cascade,
    constraint fk_group_course_assignment_course foreign key (course_id) references courses(id) on delete cascade
);

create index if not exists idx_group_course_assignments_group_id on group_course_assignments(group_id);

-- ---------------------------
-- Назначение ревьюверов курса
-- ---------------------------
create table if not exists course_reviewers (
    id bigint generated by default as identity primary key,
    course_id bigint not null,
    reviewer_id bigint not null,
    constraint uk_course_reviewer unique (course_id, reviewer_id)
);

-- ---------------------------
-- Учебные программы
-- ---------------------------
create table if not exists learning_programs (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description varchar(4000),
    cover_file_path varchar(1000),
    access_condition varchar(100) not null,
    deadline_at timestamp,
    block_after_deadline boolean not null default false
);

create table if not exists group_program_assignments (
    id bigint generated by default as identity primary key,
    group_id uuid not null,
    program_id bigint not null,
    created_at timestamp not null,
    constraint uk_group_program_assignment unique (group_id, program_id),
    constraint fk_group_program_assignment_group foreign key (group_id) references learning_groups(id) on delete cascade,
    constraint fk_group_program_assignment_program foreign key (program_id) references learning_programs(id) on delete cascade
);

create index if not exists idx_group_program_assignments_group_id on group_program_assignments(group_id);

create table if not exists program_courses (
    id bigint generated by default as identity primary key,
    program_id bigint not null,
    course_id bigint not null,
    order_index integer not null,
    deadline_at timestamp,
    block_after_deadline boolean not null default false,
    constraint uk_program_course unique (program_id, course_id),
    constraint uk_program_order unique (program_id, order_index)
);

create table if not exists program_enrollments (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    program_id bigint not null,
    enrolled_at timestamp not null,
    constraint uk_program_enrollment_user_program unique (user_id, program_id)
);

-- BOOTSTRAP INSERTIONS

INSERT INTO sections(title, description, priority) VALUES ('Остальные', 'Раздел по умолчанию', -1);
