-- Wave 0 (REF-CM-01): domain/contract alignment for course-learning area

-- 1) Drop obsolete course flags/columns
alter table courses
    drop column if exists deadline_at;

alter table courses
    drop column if exists allow_continue_after_fail;

alter table courses
    drop column if exists keep_access_after_deadline;

-- 2) Remove obsolete theory content type column
alter table lessons
    drop column if exists theory_content_type;

-- 3) Practice question type must be non-null
-- Precheck/fix: default null question_type rows to OPEN_ANSWER before adding NOT NULL.
update practice_questions
set question_type = 'OPEN_ANSWER'
where question_type is null;

alter table practice_questions
    alter column question_type set not null;

---------------------- Course Progress ---------------------------------

create table if not exists course_progress (
                                               id bigint generated by default as identity primary key,
                                               user_id bigint not null,
                                               course_id bigint not null,
                                               started_at timestamp,
                                               completed_at timestamp,
                                               status varchar(50) not null,
                                               constraint uk_course_progress_user_course unique (user_id, course_id)
);

insert into course_progress (user_id, course_id, started_at, completed_at, status)
select e.user_id,
       e.course_id,
       e.started_at,
       e.completed_at,
       case
           when e.completed_at is not null then 'COMPLETED'
           when e.started_at is not null then 'IN_PROGRESS'
           else 'NEW'
           end
from enrollments e
where not exists (
    select 1
    from course_progress cp
    where cp.user_id = e.user_id
      and cp.course_id = e.course_id
);

create index if not exists idx_course_progress_user_course
    on course_progress (user_id, course_id);

alter table enrollments
    drop column if exists started_at;

alter table enrollments
    drop column if exists completed_at;

-- Remove DB columns that no longer exist in current JPA models.

-- AppUser
alter table users
    drop column if exists lang;

-- Course
alter table courses
    drop column if exists passing_threshold_percent;

alter table courses
    drop column if exists block_after_deadline;

alter table courses
    drop column if exists include_in_overall_stats;

-- Lesson / PracticeLesson single-table columns
alter table lessons
    drop column if exists evaluate_by_correct_count;

-- ProgramCourse
alter table program_courses
    drop column if exists deadline_at;

alter table program_courses
    drop column if exists block_after_deadline;

alter table lesson_submissions
    add column if not exists started_at timestamp not null default now()::timestamp;

alter table lesson_submissions alter column submitted_at drop not null;
alter table lesson_submissions alter column started_at drop not null;

alter table lesson_submissions
    drop column if exists points_awarded;

alter table lesson_submissions
    drop column if exists completed;

update lesson_submissions
set status = 'COMPLETED'
where status = 'COMPLETE';

update lesson_submissions
set status = 'INCOMPLETED'
where status = 'INCOMPLETE';

update lesson_submissions
set status = 'REWORKING'
where status = 'REWORK';

alter table users
    add column if not exists snils varchar(255);

delete from lesson_submissions;
delete from course_progress;
delete from enrollments;
delete from program_enrollments;

UPDATE lessons l
SET full_points = COALESCE((
       SELECT SUM(pq.full_points)
       FROM practice_questions pq
       WHERE pq.lesson_id = l.id
   ), 0)
WHERE l.lesson_kind = 'PRACTICE';
