-- Wave 0 (REF-CM-01): domain/contract alignment for course-learning area

-- 1) Drop obsolete course flags/columns
alter table courses
    drop column if exists deadline_at;

alter table courses
    drop column if exists allow_continue_after_fail;

alter table courses
    drop column if exists keep_access_after_deadline;

-- 2) Remove obsolete theory content type column
alter table lessons
    drop column if exists theory_content_type;

-- 3) Practice question type must be non-null
-- Precheck/fix: default null question_type rows to OPEN_ANSWER before adding NOT NULL.
update practice_questions
set question_type = 'OPEN_ANSWER'
where question_type is null;

alter table practice_questions
    alter column question_type set not null;

---------------------- Course Progress ---------------------------------

create table if not exists course_progress (
                                               id bigint generated by default as identity primary key,
                                               user_id bigint not null,
                                               course_id bigint not null,
                                               started_at timestamp,
                                               completed_at timestamp,
                                               status varchar(50) not null,
                                               constraint uk_course_progress_user_course unique (user_id, course_id)
);

insert into course_progress (user_id, course_id, started_at, completed_at, status)
select e.user_id,
       e.course_id,
       e.started_at,
       e.completed_at,
       case
           when e.completed_at is not null then 'COMPLETED'
           when e.started_at is not null then 'IN_PROGRESS'
           else 'NEW'
           end
from enrollments e
where not exists (
    select 1
    from course_progress cp
    where cp.user_id = e.user_id
      and cp.course_id = e.course_id
);

create index if not exists idx_course_progress_user_course
    on course_progress (user_id, course_id);

alter table enrollments
    drop column if exists started_at;

alter table enrollments
    drop column if exists completed_at;
