create table if not exists group_course_assignments (
    id bigint generated by default as identity primary key,
    group_id uuid not null,
    course_id bigint not null,
    created_at timestamp not null,
    constraint uk_group_course_assignment unique (group_id, course_id),
    constraint fk_group_course_assignment_group foreign key (group_id) references learning_groups(id) on delete cascade,
    constraint fk_group_course_assignment_course foreign key (course_id) references courses(id) on delete cascade
);

create index if not exists idx_group_course_assignments_group_id on group_course_assignments(group_id);

create table if not exists group_program_assignments (
    id bigint generated by default as identity primary key,
    group_id uuid not null,
    program_id bigint not null,
    created_at timestamp not null,
    constraint uk_group_program_assignment unique (group_id, program_id),
    constraint fk_group_program_assignment_group foreign key (group_id) references learning_groups(id) on delete cascade,
    constraint fk_group_program_assignment_program foreign key (program_id) references learning_programs(id) on delete cascade
);

create index if not exists idx_group_program_assignments_group_id on group_program_assignments(group_id);
