create table if not exists lesson_submission_status_history (
    id bigint generated by default as identity primary key,
    submission_id bigint not null,
    from_status varchar(50),
    to_status varchar(50) not null,
    changed_by_admin_id bigint,
    changed_at timestamp not null,
    comment varchar(2000),
    constraint fk_submission_status_history_submission
        foreign key (submission_id) references lesson_submissions(id)
);

create index if not exists idx_submission_status_history_submission_id
    on lesson_submission_status_history(submission_id);
