spring:
  servlet:
    multipart:
      max-file-size: 100MB
  application:
    name: MEDIA-SERVICE

server:
  port: 8084

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

minio:
  domain: ${MINIO_DOMAIN:http://localhost:9000}
  endpoint: ${MINIO_URL:http://localhost:9000}
  accessKey: admin
  secretKey: adminadmin
  buckets:
    users-data: users
    courses-data: courses
    chat-data: chat-attachments

springdoc:
  api-docs:
    enabled: true
    path: /media-service/v1/api-docs
