spring:
  application:
    name: USERS-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/users_service
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog.xml
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      replication-factor: 1
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: courses
      bootstrap-servers: localhost:9092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.just.dtolib.kafka.*"
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8082
topics:
  user-actions-topic: userActions
logging:
  level:
    org.springframework.security: trace

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /users-service/v1/api-docs
