spring:
  application:
    name: SECURITY-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/security_service
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
server:
  http2:
    enabled: true
  ssl:
    key-store-type: PKCS12
    key-store: 'C:\Program Files\OpenSSL-Win64\keys\Server-keystore.p12'
    key-store-password: password
    protocol: TLS
    enabled-protocols: TLSv1.2
  port: 8083
jwt:
  token-ttl-in-minutes: 10
  cookie-name: '__Host-auth-token'
  cookie-token-key: '{"kty":"oct","k":"FA-yeE6vKp_AvZ3nJtqswg"}'

logging:
  level:
    org.springframework.security: trace
