spring:
  application:
    name: SECURITY-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5435/security_service
    username: postgres
    password: 242171e6a6d3b0701e83f72d33432a8e9fa11068
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: true
server:
  http2:
    enabled: true
  ssl:
    key-store-type: PKCS12
    key-store: 'C:\Program Files\OpenSSL-Win64\keys\Server-keystore.p12'
    key-store-password: password
    protocol: TLS
    enabled-protocols: TLSv1.2
  port: 8083
jwt:
  access-ttl-in-seconds: 1800
  refresh-ttl-in-days: 20
  secret: c2d5e5016ba507644754f5591fb5a9f43643a017c84374d161d3642f13d727402933d85082ff75e0e791e18366f241ae36ba2d4d262eea2a3fd7131ff0b4a384

logging:
  level:
    org.springframework.security: trace
