server:
  port: 8083
spring:
  application:
    name: SECURITY-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/security_service
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
jwt:
  access-ttl-in-seconds: 1800
  refresh-ttl-in-days: 20
  secret: c2d5e5016ba507644754f5591fb5a9f43643a017c84374d161d3642f13d727402933d85082ff75e0e791e18366f241ae36ba2d4d262eea2a3fd7131ff0b4a384

logging:
  level:
    org.springframework.security: trace
