spring:
  application:
    name: MENTOR-CATALOG-SERVICE

service-discovery:
  users-service:
    name: USERS-SERVICE

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
