spring:
  application:
    name: progress-service
  datasource:
    url: jdbc:postgresql://${DB_CONTAINER:localhost:5432}/progress_service
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
  instance:
    prefer-ip-address: true

server:
  port: 8089

springdoc:
  api-docs:
    enabled: true
    path: /progress-service/v1/api-docs
