spring:
  application:
    name: progress-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

server:
  port: 8089


springdoc:
  api-docs:
    enabled: true
    path: /task-checker-service/v1/api-docs
