name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # 3. Copy project to the server
      - name: Copy project to server
        uses: appleboy/scp-action@v0.1.7
        with:
          source: .
          target: /root/app
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}

      # 4. Build and deploy on the server
      - name: Build and deploy on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/app
            mvn clean install -U -Dmaven.test.skip=true
            docker-compose up -d --build
